version: '3.8'

networks:
  app_net:

services:
  spa-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: spa_web
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8009:8000"
    env_file:
      - .env.dev
    depends_on:
      - spa-db
    networks:
      - app_net

  spa-db:
    image: postgres:15
    container_name: spa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=spa_db
      - POSTGRES_PASSWORD=spa_db
      - POSTGRES_DB=spa_db_dev
    networks:
      - app_net

volumes:
  postgres_data:
